### ISSUE TITLE
Use protected instead of private

### ISSUE THREAD

**Issue by mutec** [WoltLab/com.woltlab.wcf.exporter#40]
Is there a valid reason why the WBB-exporters methods are private and not re-usable?
I'd like to extend the exporter.

**Comment by dtdesign** [comment]
Deriving from existing implementations is not a good practice due to the unstable nature of the importers and their possible side effects caused by changes to the base class. This could introduce a great deal of strange bugs or corrupted data that could take a lot of time to surface. At that point the damage could've been done and the site owner would have to bite the bullet by either doing everything again and losing content, or by sticking with what they have and also lose some content.
